-- Metering migration 1: ledger, entitlements, config, usage-summary RPC.
-- Additive only — the shipped BYOK app is unaffected.

create table ai_usage (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id),
  feature      text not null,
  model_a      text not null,
  model_b      text,
  tokens_in_a  int, tokens_out_a int,
  tokens_in_b  int, tokens_out_b int,
  cost_usd     numeric(8,6) not null,
  created_at   timestamptz not null default now()
);
create index ai_usage_user_created_idx on ai_usage (user_id, created_at);
alter table ai_usage enable row level security;
create policy own_rows_read on ai_usage for select using (auth.uid() = user_id);
revoke insert, update, delete on ai_usage from anon, authenticated;

create table entitlements (
  user_id      uuid primary key references auth.users(id),
  plan         text not null default 'free',
  status       text not null default 'active',
  period_start date,
  created_at   timestamptz not null default now()
);
alter table entitlements enable row level security;
create policy own_row_read on entitlements for select using (auth.uid() = user_id);
revoke insert, update, delete on entitlements from anon, authenticated;

create table ai_config ( id int primary key check (id = 1), value jsonb not null );
alter table ai_config enable row level security;
revoke all on ai_config from anon, authenticated;

create or replace function ai_usage_summary()
returns json language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  plan_name text; cfg jsonb; allowance numeric; lifetime bool; used numeric;
begin
  if uid is null then return json_build_object('error', 'unauthenticated'); end if;
  select plan into plan_name from entitlements where user_id = uid;
  plan_name := coalesce(plan_name, 'free');
  if plan_name = 'owner' then
    return json_build_object('plan', 'owner', 'pct_used', 0, 'exhausted', false);
  end if;
  select value into cfg from ai_config where id = 1;
  allowance := (cfg->'plans'->plan_name->>'allowance_usd')::numeric;
  lifetime  := coalesce((cfg->'plans'->plan_name->>'lifetime')::bool, false);
  if lifetime then
    select coalesce(sum(cost_usd), 0) into used from ai_usage where user_id = uid;
  else
    select coalesce(sum(cost_usd), 0) into used from ai_usage
      where user_id = uid
        and created_at >= date_trunc('month', now() at time zone 'utc');
  end if;
  return json_build_object(
    'plan', plan_name,
    'pct_used', least(100, floor(used / allowance * 100)::int),
    'exhausted', used >= allowance);
end $$;
revoke execute on function ai_usage_summary() from anon;
grant execute on function ai_usage_summary() to authenticated;
